---
title: "Publicações"
output:
  html_document:
    fig_width: 1
---

----

### Artigos Científicos

- **MATOS, LARISSA A.**; LACHOS, VICTOR H.; BALAKRISHNAN, N.; LABRA, FILIDOR V. . Influence diagnostics in linear and nonlinear mixed-effects models with censored data. Computational Statistics & Data Analysis (Print), v. 57, p. 450-464, 2013. 
</br>

- **MATOS, LARISSA A.**; PRATES, MARCOS O.; CHEN, MING-HUI; LACHOS, VICTOR H. . Likelihood Based Inference Mixed-Effects Models with Censored Responses Using the Multivariate-t Distribution. Statistica Sinica, v. 23, p. 1323-1345, 2013.
</br>

- MASSUIA, MONIQUE B.; CABRAL, CELSO RÔMULO BARBOSA; **MATOS, LARISSA A.**; LACHOS, VICTOR H. . Influence diagnostics for Student- t censored linear regression models. Statistics (Berlin), v. 49, p. 1-21, 2014.
</br>

- **MATOS, LARISSA A.**; BANDYOPADHYAY, DIPANKAR; CASTRO, LUIS M.; LACHOS, VICTOR H. . Influence assessment in censored mixed-effects models using the multivariate Student?s-. JOURNAL OF MULTIVARIATE ANALYSIS, v. 141, p. 104-117, 2015.
</br>

- **MATOS, LARISSA A.**; CASTRO, LUIS M.; LACHOS, VICTOR H. . Censored mixed-effects models for irregularly observed repeated measures with applications to HIV viral loads. TEST, v. 25, p. 627-653, 2016.
</br>

- LACHOS, VICTOR H.; **MATOS, LARISSA A.**; BARBOSA, THAIS S.; GARAY, Aldo M.; DEY, DIPAK K. . Influence diagnostics in spatial models with censored response. ENVIRONMETRICS, v. 28, p. e2464, 2017.
</br>

----

### Relatórios Técnicos

- **MATOS, LARISSA A.**; LACHOS, VICTOR H.; LIN, T.I.; CASTRO, LUIS M. . Heavy-tailed longitudinal regression models for censored data: A likelihood based perspective. RT 01 IMECC-UNICAMP, 2016.\medskip
</br>

- **MATOS, LARISSA A.**; CABRAL, CELSO RÔMULO BARBOSA; LACHOS, VICTOR H.; CASTRO, LUIS M. . Multivariate Measurement Error Models Based on Student-t Distribution with Censored Responses.  Statistics.\medskip
</br>

- LACHOS, VICTOR H.; **MATOS, LARISSA A.**; CASTRO, LUIS M.; CHEN, MING-HUI. Heavy-Tailed Longitudinal Linear Mixed Models for Multiple Censored Responses Data.\medskip
</br>

- LEMUS, MARCELA N.; LACHOS, VICTOR H.; GALARZA, CHRISTIAN E.; **MATOS, LARISSA A.** . Estimation and Diagnostics for Partially Censored Regression Models Based on Heavy-Tailed Distributions. Technical Report, 18-02, University of Connecticut.
</br>

---- 

### Programas de computador sem registro

- MATOS, LARISSA A.; PRATES, MARCOS O.; LACHOS, VICTOR H. (2011). tlmec: Linear Student-t Mixed-Effects Models with Censored Data. https://cran.r-project.org/web/packages/tlmec/index.html
</br>

- LEMUS, MARCELA N.; GALARZA, CHRISTIAN E.; MATOS, LARISSA A.; LACHOS, VICTOR H. (2018). PartCensReg: Partially Censored Regression Models Based on Heavy-Tailed Distributions. https://cran.rproject.org/web/packages/PartCensReg/index.html
</br>

----